<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="IBM955-PC09G4RA" name="com.training.functional.tests.FilterOrderTest_RTTC047" tests="8" failures="1" timestamp="05 Feb 2019 08:56:34 GMT" time="13.160" errors="0">
  <testcase name="LoginTest" time="2.907" classname="com.training.functional.tests.FilterOrderTest_RTTC047"/>
  <testcase name="movetoSales" time="1.505" classname="com.training.functional.tests.FilterOrderTest_RTTC047"/>
  <testcase name="validOrderTestWithId" time="2.067" classname="com.training.functional.tests.FilterOrderTest_RTTC047"/>
  <testcase name="validOrdertestwithname" time="1.886" classname="com.training.functional.tests.FilterOrderTest_RTTC047"/>
  <testcase name="validOrdertestbyStatus" time="1.645" classname="com.training.functional.tests.FilterOrderTest_RTTC047"/>
  <testcase name="validOrdertestbyDtAd" time="1.383" classname="com.training.functional.tests.FilterOrderTest_RTTC047"/>
  <testcase name="validOrdertestbyDtMd" time="1.762" classname="com.training.functional.tests.FilterOrderTest_RTTC047"/>
  <testcase name="validOrderTestbyTotal" time="0.005" classname="com.training.functional.tests.FilterOrderTest_RTTC047">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.training.functional.tests.FilterOrderTest_RTTC047.validOrderTestbyTotal(FilterOrderTest_RTTC047.java:126)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validOrderTestbyTotal -->
</testsuite> <!-- com.training.functional.tests.FilterOrderTest_RTTC047 -->
